ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    use_sim_time: true

    two_d_mode: true
    publish_tf: true

    # map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    odom0: odom
    odom0_config: [false, false, false,
                   false, false, false,
                   true,  true,  false,
                   false, false, true,
                   false, false, false]
    odom0_queue_size: 2

    imu0: imu/data
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, true,
                  true, true, false]
    imu0_queue_size: 2
    imu0_remove_gravitational_acceleration: true
